# syntax=docker/dockerfile:1
FROM golang:1.25-alpine AS build
WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN go test ./...
RUN CGO_ENABLED=0 go build -o /usr/local/bin/greeter ./cmd/greeter

FROM scratch
COPY --from=build /usr/local/bin/greeter /usr/local/bin/greeter
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/greeter"]
